#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d cmd web etc

bspc config border_width        1
bspc config focused_border_color "#ebbcba"
bspc config normal_border_color "#26233a"
bspc config urgent_border_color "#ebdbb2"
bspc config window_gap          2
bspc config top_padding 0  
bspc config right_padding 0  
bspc config left_padding 0  
bspc config bottom_padding 0  
# bspc config center_pseudo_tiled         true

bspc config split_ratio          0.50
bspc config borderless_monocle  true 
bspc config gapless_monocle      true
bspc config single_monocle true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=fullscreen follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a AmneziaVPN state=floating
bspc rule -a zoom state=floating border_width=0
bspc rule -a steam state=fullscreen
picom &
polybar &
feh --bg-scale ~/rosepine-birb.png &
copyq &
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle &
dunst &
udiskie -s &
xsetroot -cursor_name left_ptr &
eww daemon
xcalib -d :0 ./lcd.icc
~/touchpad
# systemctl restart python3-validity
# gentoo-pipewire-launcher &
xinput set-prop 7 335 0.2
