#!/usr/bin/bash
STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"


toggle() {
    if [[ $STATUS == "no" ]]; then
        notify-send --urgency=normal "Airplane Mode" "Turning on airplane mode!"
        getroot 'pkexec rfkill block all'
    else
        notify-send --urgency=normal "Airplane Mode" "Turning off airplane mode!"
        getroot 'pkexec rfkill unblock all'
    fi
}

class() {
    if [[ $STATUS == "no" ]]; then
        echo "inactive"
    else
        echo "active"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--class" ]]; then
    class
fi
