#!/usr/bin/bash
STATUS=$(echo $(iwctl device wlan0 show | grep Powered | cut -b 46-))
SSID=$(iwgetid -r)
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)

toggle() {
    if [[ $STATUS != "on" ]]; then
        notify-send --icon=bluetooth-offline --urgency=normal "Wi-Fi" "Wi-Fi has been turned on, you are back online!"
        iwctl device wlan0 set-property Powered on
    else
        iwctl device wlan0 set-property Powered off
        notify-send --icon=bluetooth-offline --urgency=normal "Wi-Fi" "Wi-Fi has been turned off!"
    fi
}


class() {
    if [[ $STATUS == "on" ]]; then
        echo "active"
    else
        echo "inactive"
    fi
}

speed() {
  s1=$(awk 'NR==3 {print $3}''' /proc/net/wireless)
  s2=${s1::-1}
  echo $s2
}

ssid() {
    if [[ $STATUS == "on" ]]; then
        echo $(iwgetid -r)
    else
        echo "Wifi"
    fi
}
color() {
    if [[ $STATUS == "on" ]]; then
        echo "green"

    else
        echo "red"
    fi
}
icon() {
    if [[ $STATUS == "on" ]]; then
        echo "󰤨"

    else
        echo "󰤮"
    fi
}


if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--class" ]]; then
    class
elif [[ $1 == "--ssid" ]]; then
   ssid 
elif [[ $1 == "--color" ]]; then
   color 
elif [[ $1 == "--icon" ]]; then
   icon
elif [[ $1 == "--speed" ]]; then
   speed
fi
