# corner-radius = 14
round-borders = 0 
vsync = true;
backend = "glx";
# backend = "xrender";
daemon = true;
frame-opacity = 1;
inactive-dim-fixed = true;
# transparent-clipping = true;
# blur-size = 1;
# blur-strength = 0;
# blur-background = true;
# blur-background-frame = false;
# blur-method = "gaussian";

animations = (
{
    triggers = [ "close" ];
    preset = "disappear";
    scale = 0.9;
    duration = 0.2;
},
{
    triggers = [ "show" ];
    preset = "appear";
    # direction = "up";
    scale = 0.9;
    duration = 0.2;
    curve = "cubic-bezier(0,.15,0,1)";
}, {
    triggers = [ "hide" ];
    preset = "disappear";
    scale = 1.1;
    duration = 0.2;
    curve = "cubic-bezier(0,.15,0,1)";
},
{
  triggers = [
    "geometry"
  ];
  preset = "geometry-change";
},
{
	triggers = [ "open" ];
	    scale-x = {
	        curve = "cubic-bezier(0.05, 0.9, 0.1, 1)";
	        duration = 0.4;
	        delay = 0;
	        start = 0;
	        end = 1;
	    };
	    offset-x = {
	        curve = "cubic-bezier(0.05, 0.9, 0.1, 1)";
	        duration = 0.4;
	        delay = 0;
	        start = "window-width / 2";
	        end = 0;
	    }
	    scale-y = {
	        curve = "cubic-bezier(0.05, 0.9, 0.1, 1)";
	        duration = 0.4;
	        delay = 0;
	        start = 0.5;
	        end = 1;
	    };
	    offset-y = {
	        curve = "cubic-bezier(0.05, 0.9, 0.1, 1)";
	        duration = 0.4;
	        delay = 0;
	        start = "window-height / 4";
	        end = 0;
	    };
	    opacity = {
	        curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
	        duration = 0.5;
	        start = 0.1;
	        end = 1;
	    }
})

rules: ({
  match = "class_g = 'dmenu'";
  # animations = (
  #   {
  #       triggers = [ "open", "show" ];
  #       duration = 0;
  #   },
  #   {
  #       triggers = [ "close", "hide" ];
  #       duration = 0;
  #   }
  # );
  animations = (
  	{
		triggers = [ "open", "show" ];
		preset = "appear";
		scale = 1.1;
	},
	{
		triggers = [ "close", "hide" ];
		preset = "disappear";
	}
  );
}, {
	match = "class_g = 'dwm'";
	animations = (
		{
			triggers = [ "open" ];
			preset = "fly-in";
			opacity = { duration = 0; };
		},
		{
			triggers = [ "close" ];
			preset = "fly-out";
			opacity = { duration = 0; };
		}
	);
	corner-radius = 0;
}, {
	# match = "class_g = 'st-256color'";
	# animations = (
	# 	{
	# 		triggers = [ "geometry" ];
	# 		#preset = "geometry-change";
	# 		duration = 0;
	# 	}
	# )
}, { match = "fullscreen"; corner-radius = 0; },
{ match = "monocle"; corner-radius = 0; },
{
	match = "class_g = 'Dunst'";
	animations = (
		{
			triggers = [ "open", "show" ];
			offset-x = {
				start = "(window-x - window-width)";
				end = 0;
				curve = "cubic-bezier(0,1,0,1)";
				duration = 0.7;
			};
		},
		{
			triggers = [ "geometry" ];
			preset = "geometry-change";
			duration = 0.2;
		},
		{
			triggers = [ "close", "hide" ];
			preset = "fly-out";
			direction = "left";
			duration = 0.2;
		},
	)

}, {
	match = "class_g = 'Polybar'";
	corner-radius = 0;
	animations = (
		{
			triggers = [ "open", "show" ];
			preset = "fly-in";
			direction = "down";
			curve = "cubic-bezier(0,0,0,1)";
			duration = 0.1;
		},
		{
			triggers = [ "geometry" ];
			preset = "slide-in";
			direction = "down";
			curve = "cubic-bezier(0,0,0,1)";
			duration = 0.2;
		},
		{
			triggers = [ "hide", "close" ];
			preset = "fly-out";
			direction = "down";
			curve = "cubic-bezier(0,0,0,0)";
 			duration = 0.2;
		}
	)
}, {
		match = "class_g = 'eww-mainframe'";
		animations = (
			{
				triggers = [ "open", "show" ];
				preset = "slide-in";
				direction = "down";
				duration = 0.11;
			},
			{
				triggers = [ "hide", "close" ];
				preset = "slide-out";
				direction = "down";
				duration = 0.18;
				opacity = 1;
			}
		)
}, {
		match = "class_h = 'zen'";
		frame-opacity = 0;
})
